### ISSUE TITLE
Getting receives does not work for me.

### ISSUE THREAD

**Issue by STiAT** [raintank/go-pinger#9]
Does not work for me at all, but maybe there is an issue in the code how I use it. I basically took the example and worked off that, basically looking for a thread-safe way to ping and wanted to give it a shot since go-ping does not seem to be thread safe (statistics are not .. which are quite essential if you want to know if you fail), but just can't seem to get receives.

Test-Code (a "bit" ugly and hardcoded, was just to check if it does what i want):

```
package main

import (
	"fmt"
	"log"
	"net"
	"os"
	"os/signal"
	"strings"
	"sync"
	"time"

	pinger "github.com/raintank/go-pinger"
)

type resultSet struct {
	Host    string
	Success bool
}

func main() {
	go pinghosts()

	waitforinterrupt()
	fmt.Printf("\n")
}

func pinghosts() {
	results := make(chan resultSet, 100)

	host := "google.at"

	for {
		var wg sync.WaitGroup
		resultsets := []resultSet{}
		for i := 1; i < 500; i++ {
			wg.Add(1)
			go func(host string) {
				ping(host, results)

				select {
				case x := <-results:
					resultsets = append(resultsets, x)
				default:
					fmt.Printf("Nothing to do\n")
				}
				wg.Done()
			}(host)
		}
		wg.Wait()

		for i, v := range resultsets {
			fmt.Printf("%d - %+v\n", i, v)
		}
	}
}

func ping(host string, result chan<- resultSet) {
	addr, err := resolveHost(host, "v4")

	if err != nil {
		log.Println(err)
		return
	}
	var p *pinger.Pinger
	p, err = pinger.NewPinger("ipv4", 1000)

	if err != nil {
		log.Fatal(err)
		return
	}
	stats, err := p.Ping(net.ParseIP(addr), 2, time.Second*2)
	if err != nil {
		log.Println(err)
		return
	}

	res := resultSet{Host: host}
	if stats.Sent != stats.Received {
		res.Success = false
		fmt.Printf("%s Sent: %d\n", host, stats.Sent)
		fmt.Printf("%s Received: %d\n", host, stats.Received)
		result <- res
	} else {
		res.Success = true
		result <- res
	}
}

func waitforinterrupt() {
	var endwaiter sync.WaitGroup
	endwaiter.Add(1)
	var signalchannel chan os.Signal
	signalchannel = make(chan os.Signal, 1)
	signal.Notify(signalchannel, os.Interrupt)
	go func() {
		<-signalchannel
		endwaiter.Done()
	}()
	endwaiter.Wait()
}

func resolveHost(host, ipversion string) (string, error) {
	addrs, err := net.LookupHost(host)
	if err != nil || len(addrs) < 1 {
		return "", fmt.Errorf("failed to resolve hostname to IP")
	}

	for _, addr := range addrs {
		if ipversion == "any" {
			return addr, nil
		}

		if strings.Contains(addr, ":") || strings.Contains(addr, "%") {
			if ipversion == "v6" {
				return addr, nil
			}
		} else {
			if ipversion == "v4" {
				return addr, nil
			}
		}
	}

	return "", fmt.Errorf("failed to resolve hostname to valid IP")
}
```

Any ideas why this is failing?

As  a side note, is it possible to run it unprivileged?

**Comment by woodsaj** [comment]
There are quite a few issues with your example code.
1) you should only be creating 1 pinger.Pinger instance for the process. You are currently trying to create a new one for each ping you send.
2) after calling `p, err := ping.NewPinger("ipv4", 1000)` , you need to call `p.Start()`.  The raw socket used to listen for the ping responses is not started until Start() is called.
3) unrelated to your use of the go-pinger package, your code is vulnerable to data race conditions, specifically multiple goroutines concurrently appending to the same resultsets slice.

here is a working version of what you are trying to do. https://gist.github.com/woodsaj/310ffafb1abde66b9373347d3eb12db9

**Comment by woodsaj** [comment]
> As a side note, is it possible to run it unprivileged?

Unfortunately not.  The implementation here uses raw sockets, which require elevated privileges.  You dont need full root privileges, just enough permissions to use raw sockets, ie CAP_NET_RAW see https://linux.die.net/man/7/capabilities for more details.
